version: '3.8'
services:
  mysql:
    platform: linux/x86-64
    image: postgres:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: example
      POSTGRES_PASSWORD: postgres